name: Node

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    name: Test Node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: build package
        run: npm run build
      - name: run tests
        run: npm run test

  types:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    name: Test Types on Node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: check types
        run: npm run check-types

  summary:
    runs-on: ubuntu-latest
    needs:
      - test
      - types
    if: always()
    name: test-summary
    steps:
      - name: Test summary status
        run: if ${{ needs.test.result != 'success' && needs.test.result != 'skipped' }}; then exit 1; fi
      - name: Types summary status
        run: if ${{ needs.types.result != 'success' && needs.types.result != 'skipped' }}; then exit 1; fi
